language: node_js

node_js:
    - "8"
script:
    - echo "Deploying!"
install:
    - npm install mocha -g
    - npm install chai --save-dev
    - npm install -g firebase-tools

after_success:
    - mocha test
    - firebase deploy --token $FIREBASE_TOKEN
