language: node_js

node_js:
    - "8"
script:
    - echo "Deploying!"
install:
    - npm install -g firebase-tools
    - npm install --save firebase    

after_success:
    - firebase deploy --token $FIREBASE_TOKEN
